language: php

php:
    - 5.3
    - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php -- --quiet
    - php composer.phar install
    - php app/console propel:database:create --env=test

script: phpunit