imports:
    - { resource: config_dev.yml }
    
propel:
    dbal:
       driver: mysql
       user: ledjassa
       password: "passledjassa"
       dsn: mysql:host=localhost;dbname=ledjassa;charset=UTF8
        
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
