imports:
    - { resource: config.yml }
    - { resource: @LeDjassaAdsBundle/Resources/config/services.xml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    auth_mode:  login
    host:       smtp.auportdadjame.com
    port:       587
    username:   postmaster@auportdadjame.com
    password:   "limperial123"
    spool:     { type: memory }

# Propel Configuration
propel:
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"
    dbal:
       driver:               mysql
       user:                 auportdadjame
       password:             "limperial123"
       dsn:                  mysql:host=mysql51-75;dbname=auportdadjame;charset=UTF8
       options:              {}
       attributes:           {}

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
