# Propel Configuration
propel:
    dbal:
       driver:               mysql
       user:                 ledjassa
       password:             "passledjassa"
       dsn:                  mysql:host=localhost;dbname=ledjassa;charset=UTF8
       options:              {}
       attributes:           {}

parameters:
    database_driver:   mysql
    database_host:     localhost
    database_port:     ~
    database_name:     ledjassa
    database_user:     ledjassa
    database_password: ledjassa

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt